### ISSUE TITLE
Issue 15 issues

### ISSUE THREAD

**Issue by hged13** [nathanbollig/rt-quic-db#114]
When loading saved well condition data: mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; 

KeyError: 'sample' when trying to save data.

Data will save once for a selected well, but will load into a new un-edited well when the well data is selected.

**Comment by nathanbollig** [comment]
Hannah, 

Can you please specify the MySQL command you ran to update your local database for this development?

**Comment by nathanbollig** [comment]
Please review and read comments to new commit on this branch, which discusses and proposes resolution of data loading issues. More to come for the data saving issue.
