### ISSUE TITLE
Accomodate alternative plate template dimensions

### ISSUE THREAD

**Issue by nathanbollig** [nathanbollig/rt-quic-db#123]
We need to comprehensively evaluate system changes necessary for non-standard plate template dimensions.

To start, let's play with the 384-Well data.

Example issues:
- Ensure plate template dimensions match the data embedded in the .csv file uploaded
- Ensure that the dimensions of charts layout in View Assay matches the designated plate template dimensions
- Test Well Edit, Assay Edit/Delete, and other functionality that relates to assays
- Review data stored in the database to make sure it is sensible with alternative plate template dimensions

What else do we need to test? Can we come up with a design plan?

**Comment by nathanbollig** [comment]
## Design

### Upload Assay
Before proceeding with an assay upload, we should validate that the dimensions of the data in the provided .csv file match the dimensions in the Plate Template record specified by the user.

### View Assay
The grid of fluorescence curves should have rows and columns as specified in the plate template record attached to the assay.

### Additional Considerations
Hannah to test all workflows with 384-Well data and describe any additional changes required by either (1) changes in plate template dimensions or (2) using plates that are visually larger in size. Please edit this post to add in subsections as needed, including technical notes and test plan if appropriate.

## Technical

### Upload Assay
1. `data_upload_util.py` > `parse_rt_quic_csv()`: Add a third return value `implied_dims`, which will be a tuple.
   - Option 1; If row names follow the typical convention of 'A01', 'A02', ..., 'B01', ..., then we can infer a dimensions across the plate's row axis (number of alphabetic characters prefixed to each well name) and across the plates column axis (number of numeric values following the alphabetic character). The tuple length will then be 2 as `(num of rows on plate, num of cols on plate)`. This calculation should be placed at the end of the parse function around Line 71 and use the available keys of the `rows` dictionary.
   - Option 2: The row names may not follow the typical convention. In that case, we cannot infer the 2-dimensional layout of data from the .csv. The tuple is of length 1 and represents the flattened dimension, like `(num of rows on plate * num of cols on plate,)`. 


2. `model.py` > `create_assay()`: Move Line 95 (invocation of  `parse_rt_quic_csv()`) to before the create assay line, to prevent shell assay records from being created if the parsing fails.

3. Write a method in `ManagePlate` class (`model.py`) with the following API: `get_plate_dims(self, plate_ID)`
It takes in a plate ID and returns the tuple (number of rows, number of cols) as specified in the corresponding plate template record.

4. Write a method in `ManageAssay` class (`model.py`) sort of like this:

```python
def validate_plate_dimensions(self, data, dims):
     # Get plate ID
     plate_ID = data.get('plate')
     if plate_ID is None, return False
     
     # Get dimensions from plate template
     plateModel = ManagePlate(self.session)
     plate_dims = plateModel.get_plate_dims(plate_ID)
     
     # Check that dimensions are the same
     output = False     
     if len(dims) == 2 and dims == plate_dims:
          output = True
     elif len(dims) == 1 and dims[0] == plate_dims[0] * plate_dims[1]:
          output = True

     return output
``` 

5. `model.py` > `create_assay()`: After calling `parse_rt_quic_csv()` but before creating an assay, invoke `self.validate_plate_dimensions(data, implied_dims)` and throw a `ValidationError` if false.

6. `app_server.py` > `upload_plate()`: I recommend wrapping the `create_assay()` call in a try-except and print a flash message with informative error message if one is encountered.

### View Assay
`app_server.py` > `get_viz_data()`: The dimensions of the grid shown in View Assay (with all wells selected) appears to come from the `rows` and `cols` returned by `wcModel.get_assay_viz_dataGrid(assay_id)`. Note these are packaged into a json object retrieved at the front end via a .getJSON call. 

`get_assay_viz_dataGrid()` parses the well names into variables like
```
rows = ['A', 'B', ..., 'H']
cols = ['01', '02', ..., '12]
well_conditions = [[], [], ..., []]
len(well_conditions) = len(rows)
len(well_conditions[0]) = len(cols)
len(well_conditions[0][0]) = number of fluorescence timepoints
```
This logic depends on the well names and therefore is less general than the two option handling of well names proposed for Upload Assay above. This issue is documented in #130 and will be held for later development.

However, note that if validation is imposed at Upload Assay, then these well names will be consistent with plate template dimensions. Since the structure of `well_conditions` (passed as `result` in the json object) is used to create the data grid, and the structure of `well_conditions` is based on rows and columns inferred from well names, then with validation we can assume that the dimensions of the data grid will be consistent with plate dimensions. (This will not work if well names are not named according to the description of Option 1 above. However, this case will be handled separately in #130.) Therefore, no changes are required for View Assay.

Except for a minor recommendation:
1. `application_main.js` Line 187. This comment refers to adding row headers, but it actually is adding column headers. This should be changed.

## Test Plan
### Upload Assay
#### Create test .csv files:

Less rows
   - 6x12a: `1-21-20CationTest3_sec` with all 'G' and 'H' rows removed
   - 6x12b: `1-27-20SaponinTest_sec` with all 'A' and 'B' rows removed
   - 6x12aT: `96_transposed` with all 'G' and 'H' columns removed
   - 6x12bT: `96_transposed` with all 'A' and 'B' columns removed

Less columns
   - 8x10a: `2-6-20AlmondExtract_sec` with all '11' and '12'  rows removed
   - 8x10b: `2-6-20BoardmanExtract_sec` with all '05' and '06' rows removed
   - 8x10aT: `96_transposed` with all columns ending in '11' and '12' removed
   - 8x10bT: `96_transposed` with all columns ending in '05' and '06' removed
 
More rows
   - 12x12a: `3-13-20GlassDeconTest1_sec` with 'A' through 'D' rows copied as 'I' through 'L' to simulate 12 plate rows
   - 12x12b: `1-21-20CationTest3_sec` with 'B', 'D', 'F', and 'H' rows copied as 'I' through 'L' to simulate 12 plate rows
   - 12x12aT: `96_transposed` with 'A' through 'D' columns copied as 'I' through 'L' to simulate 12 plate rows
   - 12x12bT: `96_transposed` with 'B', 'D', 'F', and 'H' rows copied as 'I' through 'L' to simulate 12 plate rows

More columns
   - 8x14a: `1-27-20SaponinTest_sec` with rows ending in '01' and '02' copied as rows ending in '13' and '14' to simulate 14 plate columns
   - 8x14b: `2-6-20AlmondExtract_sec` with rows ending in '07' and '09' copied as rows ending in '13' and '14' to simulate 14 plate columns
   - 8x14aT: `96_transposed` with '01' and '02'' columns copied as '13' and '14' to simulate 14 plate columns
   - 8x14bT: `96_transposed` with '07' and '09' columns copied as '13' and '14' to simulate 14 plate columns

Transposed dimensions relative to 8x12
   - 12x8: 12x12b with '01' through '04' rows removed to simulate 8 plate columns
   - 12x8T: 12x12bT with '01' through '04' columns removed to simulate 8 plate columns

Larger plates
   - 24x12: 12x12b with all rows copied (ending up through 'P') to simulate 24 plate rows
   - 24x12T: 12x12bT with all rows copied (ending up through 'P') to simulate 24 plate rows
   - 16x24T: `384_transposed`
   - 13x24T: cut three plate rows from 16x24T
   - 16x21T: cut three plate columns from 16x24T
   - 13x21T: cut three plate rows and three plate columns from 16x24T

#### Test Upload Assay

For each .csv file, test with 
  - 1 plate template of appropriate dimensions (e.g. 8x10bT with a plate template having 8 rows 10 columns)
  - 1 plate template if inappropriate dimensions (e.g. 12x8 with standard 96-well plate template having 8 rows and 12 columns)

(Total of 48 test cases)

### View Assay

For each assay uploaded in the above Upload Assay tests (should be 24 test cases), look at the View Assay grid to ensure it has the appropriate dimensions. Note that, for example, 12x8 and 12x8T should both appear as 12 plate rows and 8 plate columns because the transposition (T label) refers only to the transposition of matrix of wells and timepoints in the .csv file.

**Comment by hged13** [comment]
NOTES:


Uploading a  384 wells assay works with template of 96 well data.
View Assay works, but as known the data is not displayed In the way that is specified by the template.
‘Well Name’ for well condition data does not match the specified template.
Update Assay and Delete Assay functionality appear to work as expected with the 384 well data, even if uploaded with the wrong template. 


TEST PLAN (check existing functionalities and verify them in the DB):

Test the edited files with a template that matches the edited dimensions, and a template that contains incorrect dimensions. Verify that an error is thrown if the dimensions of the template do not match the dimensions of the CSV file. (Unless transposition is relevant.) Verify that no shell assay record was created. 

After Updates re-test Well-edit, and assay edit/ delete to verify that it still works as expected. 

For at least one file from each of the categories ‘Less rows, Less columns, More rows, More columns, Transposes dimensions, and Larger plates’ perform the following tests:


After uploading assay, navigate to Assay View. 
Add Well edit data to a single well. Save the data and verify that the data appears for the expected well in the web-form and in the database.
In the database, the ‘well_name’  column under the ‘well_condition’ table should match the dimensions of the template. Rows are denoted alphabetically from A - Z. Columns are denoted numerically from 1: . For example,  8x12 well data should contain well names A01-A12, B01-B12, etc. ending with Row H.  Well Data of different dimensions should be formatted differently in the database. 

 Select ‘clear selection’ the and verify that the data has been removed from the web-form and from the database.

Repeat this test with a group of at least three wells. Verify that all of the wells display the saved data in the web-form and the database.


Navigate to Edit-Assay. Verify that update assay and delete assay functionalities still work as expected.

**Comment by nathanbollig** [comment]
Great additions to the plan. I have added this to the main design plan post above (feel free to edit as needed).

A question - What do you mean by this? ```‘Well Name’ for well condition data does not match the specified template.```

Also a few notes:
 - 'clear selection' doesn't clear data from the wells, it just changes all wells on the UI from selected to unselected
 - The 'dimensions of the .csv' file will never be the dimensions of the template, because all wells in the assay are listed as either rows or columns in the .csv. So the dimensions of the .csv with either be (nrows*ncol, n_timepoints) or (n_timepoints, nrows*ncol) if of the transposed format, where nrows and ncol are the number of rows and cols on the plate represented by the assay data. Does that make sense?

The design plan looks good to me. What do you think? Ready to move forward to development?

**Comment by hged13** [comment]
I looked back at the .csv and understand the formatting now, that makes sense! And gotcha on ‘clear selection’. When testing I’ll just manually clear the well condition data. 

I just meant that the correct column and row dimensions should be represented here under well_name  in the well_condition table, which I guess should already  be the case if the view formatting is changed to match the specified template. 



Looks good to me! Ready to move forward.
